### ISSUE TITLE
Missing file to build

### ISSUE THREAD

**Issue by SystemDataModel** [fmidev/smartmet-server#6]
Hello,

The makefile calls the following line:
include $(shell echo $${PREFIX-/usr})/share/smartmet/devel/makefile.inc

But the included file does not exist.

Is there any additional dependency ?

I wish you happy holidays

**Comment by mheiskan** [comment]
The RPM dependencies are listed in smartmet-server.spec. We currently do not support any other build systems.
The relevant dependency here is this line:

BuildRequires: smartmet-library-macgyver-devel >= 24.11.27

You can install all required RPM dependencies with "sudo debuginfo-install smartmet-server.spec"

**Comment by mheiskan** [comment]
Sorry, I answered too quickly while taking a long call. The correct command for installing build dependencies is actually

sudo yum-builddep smartmet-server.spec
